[programs.devnet]
myepicproject = "5wwaDDAdn8bfk5z18oQPFcZKxuip24UaRSeSjJmA9LYK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/ryan/.config/solana/id.json"

[scripts]
test = "node app/tests/myepicproject.js"
